In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8-darkgrid')
%matplotlib inline

In [2]:
#load international matches data
matches = pd.read_csv('../data/raw/results.csv')

#display first few rows of the dataframe
matches.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [4]:
print(f"Total matches: {len(matches)}")
print(f"Date range: {matches['date'].min()} to {matches['date'].max()}")
matches.info()

Total matches: 48850
Date range: 1872-11-30 to 2025-11-20
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48850 entries, 0 to 48849
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        48850 non-null  object
 1   home_team   48850 non-null  object
 2   away_team   48850 non-null  object
 3   home_score  48849 non-null  float64
 4   away_score  48849 non-null  float64
 5   tournament  48850 non-null  object
 6   city        48850 non-null  object
 7   country     48850 non-null  object
 8   neutral     48850 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.0+ MB

In [26]:
goalscorers = pd.read_csv('../data/raw/goalscorers.csv')
goalscorers.head()

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

In [45]:
ronaldo_goals = goalscorers[goalscorers['scorer'].str.contains('Cristiano Ronaldo', case=False, na=False)]
print(f"Ronaldo goals found: {len(ronaldo_goals)}")
ronaldo_goals.head()

Ronaldo goals found: 108

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
23831,2004-06-12,Portugal,Greece,Portugal,Cristiano Ronaldo,90.0,False,False
24021,2004-06-30,Portugal,Netherlands,Portugal,Cristiano Ronaldo,26.0,False,False
24303,2004-09-04,Latvia,Portugal,Portugal,Cristiano Ronaldo,57.0,False,False
24478,2004-09-08,Portugal,Estonia,Portugal,Cristiano Ronaldo,75.0,False,False
24755,2004-10-13,Portugal,Russia,Portugal,Cristiano Ronaldo,39.0,False,False

In [3]:
matches_por = matches[(matches['home_team'] == 'Portugal') | (matches['away_team'] == 'Portugal')]
#check number of matches involving Portugal
print(f"Total matches involving Portugal: {len(matches_por)}")

Total matches involving Portugal: 691

In [17]:
matches_por_w = matches[
    (matches['home_team'] == 'Portugal') & (matches['home_score'] > matches['away_score']) | 
    (matches['away_team'] == 'Portugal') & (matches['away_score'] > matches['home_score'])]
#winrate calculation
winrate_por = len(matches_por_w) / len(matches_por)
print(f"Portugal winrate: {winrate_por}")

Portugal winrate: 0.5007235890014472

In [14]:
matches['tournament'].unique()

array(['Friendly', 'British Home Championship', 'Évence Coppée Trophy',
       'Muratti Vase', 'Copa Lipton', 'Copa Newton',
       'Copa Premio Honor Argentino', 'Olympic Games',
       'Copa Premio Honor Uruguayo', 'Far Eastern Championship Games',
       'Copa Roca', 'Copa América', 'Inter-Allied Games', 'Peace Cup',
       'Open International Championship', 'Soccer Ashes',
       'Copa Chevallier Boutell', 'Nordic Championship',
       'Central European International Cup', 'Baltic Cup', 'Balkan Cup',
       'Central American and Caribbean Games', 'FIFA World Cup',
       'Copa Rio Branco', 'FIFA World Cup qualification',
       'Bolivarian Games', 'CCCF Championship', 'NAFC Championship',
       'Copa Oswaldo Cruz', 'Asian Games', 'Pan American Championship',
       'Copa del Pacífico', "Copa Bernardo O'Higgins",
       'AFC Asian Cup qualification', 'Atlantic Cup', 'AFC Asian Cup',
       'African Cup of Nations', 'Copa Paz del Chaco',
       'Merdeka Tournament', 'UEFA Euro qualification',
       'Southeast Asian Peninsular Games', 'African Friendship Games',
       'UEFA Euro', 'Windward Islands Tournament',
       'African Cup of Nations qualification', 'Vietnam Independence Cup',
       'Copa Carlos Dittborn', 'Phillip Seaga Cup',
       'CONCACAF Championship', 'Copa Juan Pinto Durán', 'Arab Cup',
       'South Pacific Games', 'Zambian Independence Tournament',
       'CONCACAF Championship qualification', 'Copa Artigas',
       'All-African Games', 'GaNEFo', 'Copa América qualification',
       "King's Cup", 'Gulf Cup', 'Indonesia Tournament', 'Korea Cup',
       'Palestine Cup', 'Brazil Independence Cup', 'Copa Ramón Castilla',
       'Oceania Nations Cup', 'CECAFA Cup', 'Kuneitra Cup',
       'Copa Félix Bogado', 'Real Madrid 75th Anniversary Cup',
       'Beijing International Friendship Tournament',
       'Southeast Asian Games', 'Kirin Cup',
       'CFU Caribbean Cup qualification', 'CFU Caribbean Cup',
       'Amílcar Cabral Cup', 'FIFA 75th Anniversary Cup',
       'Indian Ocean Island Games',
       'Guangzhou International Friendship Tournament', 'Mundialito',
       'South Pacific Mini Games', 'West African Cup', 'Nehru Cup',
       'Merlion Cup', 'Trans-Tasman Cup', 'Great Wall Cup',
       'South Asian Games', 'UDEAC Cup', 'Rous Cup',
       'CONMEBOL–UEFA Cup of Champions', 'Miami Cup',
       'Lunar New Year Cup', 'Arab Cup qualification',
       'Tournoi de France', 'Malta International Tournament',
       'Four Nations Tournament', 'Matthews Cup',
       'Tournament Burkina Faso', 'Marlboro Cup', 'Island Games',
       'NAFU Championship', 'Dynasty Cup', 'Dakar Tournament',
       'UNCAF Cup', 'Scania 100 Tournament', 'Gold Cup', 'USA Cup',
       'Jordan International Tournament', 'Confederations Cup',
       'East Asian Games', 'United Arab Emirates Friendship Tournament',
       'Joe Robbie Cup', 'Oceania Nations Cup qualification',
       'Simba Tournament', 'SAFF Cup', 'AFF Championship',
       'King Hassan II Tournament', 'Cyprus International Tournament',
       'Dunhill Cup', 'COSAFA Cup qualification', 'COSAFA Cup',
       'Gold Cup qualification', 'AFF Championship qualification',
       'SKN Football Festival', "Four Nations' Cup", 'UNIFFAC Cup',
       'WAFF Championship', 'Millennium Cup',
       'Cup of Ancient Civilizations', "Prime Minister's Cup",
       'Unity Cup', 'The Other Final', 'EAFF Championship',
       'TIFOCO Tournament', 'Afro-Asian Games', 'AFC Challenge Cup',
       'FIFI Wild Cup', 'ELF Cup', 'Viva World Cup',
       'AFC Challenge Cup qualification', "Coupe de l'Outre-Mer",
       'VFF Cup', 'Corsica Cup', 'Dragon Cup', 'ABCS Tournament',
       'Nile Basin Tournament', 'Nations Cup', 'Copa Confraternidad',
       'Pacific Games', 'Superclásico de las Américas',
       'Kirin Challenge Cup', 'Tynwald Hill Tournament', 'OSN Cup',
       'CONIFA World Football Cup', 'Niamh Challenge Cup',
       'CONIFA European Football Cup', 'Benedikt Fontana Cup',
       'ConIFA Challenger Cup', 'Hungary Heritage Cup', 'World Unity Cup',
       'Pacific Mini Games', 'Intercontinental Cup',
       'UEFA Nations League', 'CONCACAF Nations League qualification',
       'Atlantic Heritage Cup', 'Inter Games', 'CONCACAF Nations League',
       'Three Nations Cup', 'Mahinda Rajapaksa Cup', 'Navruz Cup',
       'CONIFA Africa Football Cup', 'CONIFA South America Football Cup',
       "MSG Prime Minister's Cup", 'Tri Nation Tournament',
       'CAFA Nations Cup', 'Mauritius Four Nations Cup',
       'CONIFA World Football Cup qualification', 'CONIFA Asia Cup',
       'FIFA Series', 'Marianas Cup', 'Tri-Nations Series',
       'ASEAN Championship qualification', 'ASEAN Championship',
       'EAFF Championship qualification', 'Mapinduzi Cup',
       'Canadian Shield', 'Outrigger Challenge Cup',
       'South Asian Super Cup', 'CONCACAF Series',
       'Al Ain International Cup'], dtype=object)

In [15]:
matches_wc = matches[matches['tournament'] == 'FIFA World Cup']

In [43]:
matches_por_wc = matches_wc[(matches_wc['home_team'] == 'Portugal') | (matches_wc['away_team'] == 'Portugal')]
print(f"Total World Cup matches involving Portugal: {len(matches_por_wc)}")
#find winrate in World Cup matches
matches_por_wc_w = matches_wc[
    (matches_wc['home_team'] == 'Portugal') & (matches_wc['home_score'] > matches_wc['away_score']) | 
    (matches_wc['away_team'] == 'Portugal') & (matches_wc['away_score'] > matches_wc['home_score'])]
winrate_por_wc = len(matches_por_wc_w) / len(matches_por_wc)
print(f"Portugal World Cup winrate: {winrate_por_wc}")
matches_por_wc = matches_por_wc.sort_values('date', ascending=False)
matches_por_wc.iloc[:10]
ronaldo_goals_wc = ronaldo_goals[ronaldo_goals['date'].isin(matches_por_wc['date'])]
print(f"Ronaldo World Cup goals found: {len(ronaldo_goals_wc)}")
# Ronaldo-era Portugal WC matches (2006 onwards)
matches_wc_ronaldo_era = matches_wc[
    ((matches_wc['home_team'] == 'Portugal') | (matches_wc['away_team'] == 'Portugal')) &
    (matches_wc['date'] >= '2006-01-01')
]
print(f"Portugal WC matches in Ronaldo era: {len(matches_wc_ronaldo_era)}")
#ronaldo wc scoring rate
ronaldo_goals_wc_era = ronaldo_goals_wc[ronaldo_goals_wc['date'].isin(matches_wc_ronaldo_era['date'])]
ronaldo_wc_scoring_rate = len(ronaldo_goals_wc_era) / len(matches_wc_ronaldo_era)
print(f"Ronaldo World Cup scoring rate (goals per match): {ronaldo_wc_scoring_rate}")

Total World Cup matches involving Portugal: 35
Portugal World Cup winrate: 0.4857142857142857
Ronaldo World Cup goals found: 8
Portugal WC matches in Ronaldo era: 23
Ronaldo World Cup scoring rate (goals per match): 0.34782608695652173

In [35]:
# Portugal vs Colombia head-to-head
h2h = matches_por[
    ((matches_por['home_team'] == 'Colombia') | (matches_por['away_team'] == 'Colombia'))
]
print(f"Portugal vs Colombia matches: {len(h2h)}")
h2h[['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament']]

Portugal vs Colombia matches: 0

Empty DataFrame
Columns: [date, home_team, away_team, home_score, away_score, tournament]
Index: []

In [36]:
rankings = pd.read_csv('../data/raw/fifa_ranking-2024-06-20.csv')
rankings.head()

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,140.0,Brunei Darussalam,BRU,2.0,0.0,140,AFC,1992-12-31
1,33.0,Portugal,POR,38.0,0.0,33,UEFA,1992-12-31
2,32.0,Zambia,ZAM,38.0,0.0,32,CAF,1992-12-31
3,31.0,Greece,GRE,38.0,0.0,31,UEFA,1992-12-31
4,30.0,Algeria,ALG,39.0,0.0,30,CAF,1992-12-31

In [39]:
#get colombia's latest ranking
col_rank = rankings[rankings['country_full'] == 'Colombia']['rank'].values[-1]
print(f"Colombia's latest FIFA ranking: {col_rank}")

Colombia's latest FIFA ranking: 12.0

In [40]:
#find colombia's strength (winrate, goals scored, etc.)
matches_col = matches[
    (matches['home_team'] == 'Colombia') | (matches['away_team'] == 'Colombia')]
matches_col_w = matches[(matches['home_team'] == 'Colombia') & (matches['home_score'] > matches['away_score']) | 
                        (matches['away_team'] == 'Colombia') & (matches['away_score'] > matches['home_score'])]
winrate_col = len(matches_col_w) / len(matches_col)
print(f"Colombia winrate: {winrate_col}")
goals_col = 0
for _, match in matches_col.iterrows():
    if match['home_team'] == 'Colombia':
        goals_col += match['home_score']
    else:
        goals_col += match['away_score']
avg_goals_col = goals_col / len(matches_col)
print(f"Colombia average goals per match: {avg_goals_col}")

Colombia winrate: 0.4037854889589905
Colombia average goals per match: 1.2870662460567823

In [44]:
#same analysis for Uzbekistan
matches_uzb = matches[
    (matches['home_team'] == 'Uzbekistan') | (matches['away_team'] == 'Uzbekistan')]
h2h_uzb = matches_por[((matches_por['home_team'] == 'Uzbekistan') | (matches_por['away_team'] == 'Uzbekistan'))]
print(f"Portugal vs Uzbekistan matches: {len(h2h_uzb)}")
matches_uzb_w = matches[(matches['home_team'] == 'Uzbekistan') & (matches['home_score'] > matches['away_score']) | 
                        (matches['away_team'] == 'Uzbekistan') & (matches['away_score'] > matches['home_score'])]
winrate_uzb = len(matches_uzb_w) / len(matches_uzb)
print(f"Uzbekistan winrate: {winrate_uzb}")
goals_uzb = 0
for _, match in matches_uzb.iterrows():
    if match['home_team'] == 'Uzbekistan':
        goals_uzb += match['home_score']
    else:
        goals_uzb += match['away_score']
avg_goals_uzb = goals_uzb / len(matches_uzb)
print(f"Uzbekistan average goals per match: {avg_goals_uzb}")
uzb_rank = rankings[rankings['country_full'] == 'Uzbekistan']['rank'].values[-1]
print(f"Uzbekistan's latest FIFA ranking: {uzb_rank}")

Portugal vs Uzbekistan matches: 0
Uzbekistan winrate: 0.4813753581661891
Uzbekistan average goals per match: 1.7392550143266476
Uzbekistan's latest FIFA ranking: 62.0

In [ ]:
#Ronaldo Era Portugal Analysis
def opp_rank(opponent, date):
    ranking_date = rankings[rankings["rank_date"] <= date].sort_values("rank_date", ascending=False)
    rank = ranking_date[ranking_date["country_full"] == opponent]["rank"]
    if not rank.empty:
        return int(rank.values[0])
    else:
        return np.nan
    
matches_por_ronaldo_era = matches_por[matches_por['date'] >= ronaldo_goals['date'].min()]
matches_por_ronaldo_era["opp_rank"] = m

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
28292,2004-06-12,Portugal,Greece,1.0,2.0,UEFA Euro,Porto,Portugal,False
28314,2004-06-16,Portugal,Russia,2.0,0.0,UEFA Euro,Lisbon,Portugal,False
28345,2004-06-20,Portugal,Spain,1.0,0.0,UEFA Euro,Lisbon,Portugal,False
28362,2004-06-24,Portugal,England,2.0,2.0,UEFA Euro,Lisbon,Portugal,False
28372,2004-06-30,Portugal,Netherlands,2.0,1.0,UEFA Euro,Lisbon,Portugal,False

In [50]:
rankings.head()

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,140.0,Brunei Darussalam,BRU,2.0,0.0,140,AFC,1992-12-31
1,33.0,Portugal,POR,38.0,0.0,33,UEFA,1992-12-31
2,32.0,Zambia,ZAM,38.0,0.0,32,CAF,1992-12-31
3,31.0,Greece,GRE,38.0,0.0,31,UEFA,1992-12-31
4,30.0,Algeria,ALG,39.0,0.0,30,CAF,1992-12-31